### PR TITLE
Add expect(value).toBeRegExp() matcher

### PR DESCRIPTION
**Pull request by jacobwarduk**

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks a lot for this @jacobwarduk, this is a great PR. I've squashed the commits and also updated the npm dependencies while I'm in there. I've run out of time this evening and have pushed to https://github.com/JamieMason/Jasmine-Matchers/tree/jacobwarduk-master.

All that is left now is to update the README with the new matcher, and also I think we should create an equivalent asymmetric matcher `any.regExp()`.

Thanks again for this.

**Comment by JamieMason** [comment]
Just noticed as well that the updated version of `xo` has some new lint errors to complain about, I'll get those sorted.

**Comment by jacobwarduk** [comment]
> All that is left now is to update the README with the new matcher, and also I think we should create an equivalent asymmetric matcher any.regExp().

I shall do this by noon tomorrow.

**Comment by JamieMason** [comment]
FYI this has been merged into [pull-request/65-toberegexp](https://github.com/JamieMason/Jasmine-Matchers/tree/pull-request/65-toberegexp) and will be released once the build passes. If there are any amendments, please branch off pull-request/65-toberegexp and continue from there 👍 .

**Comment by JamieMason** [comment]
Released in 3.2.0

**Pull request closed without merging**
