### PR TITLE
Add TypeScript declarations for typing

### LINKED ISSUE #59: Adding this library to an Angular 2 project using Jasmine
Hi all! 

I think this is not an issue but can be an improvement in the doc.

I'm developing an Angular 2 RC5 app with Jasmine and I'm trying to load this library.

What I've done is:

In a `unit-tests.html` file I've included the following:
```

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>Ng App Unit Tests</title>
    <link rel="stylesheet" href="node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    <!-- #1. Polyfills -->
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <!-- #2. Zone.js dependencies -->
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/zone.js/dist/async-test.js"></script>
    <script src="node_modules/zone.js/dist/fake-async-test.js"></script>
    <!-- #3. Add specs dependencies -->
    <script src="app/treeNode.spec.ts"></script>
    <script src="app/template.spec.ts"></script>
    <script src="app/services/tree.side.service.spec.ts"></script>
    <script src="app/services/tree.service.spec.ts"></script>
    <!-- #4. Add Jasmine dependencies -->
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
    <script src="node_modules/jasmine-expect/dist/jasmine-matchers.js"></script>
[...]
```

And then, I've created a Spec file, like this:

```
describe('Service: TreeService', () => {

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [
                {provide: TreeService, useClass: TreeService},
                [...]
            ]
        })
    });

    it('get nodes',
        inject(
            [TreeService], fakeAsync((service: TreeService, backend: MockBackend) => {
                let res: TreeNode[];
                service.provider = '/test/api/treeNodes';
                service.getNodes();
                service.nodes.subscribe((response) => {
                    res = response as TreeNode[];
                });
                tick(500);
                expect(res).toBeArray();
                expect(res).toBeNonEmptyArray();
                expect(res.length).toBeGreaterThan(0);
            })));
});
```

But when I run the app, with `npm test` this error occurs:
```
app/services/tree.service.spec.ts(39,29): error TS2339: Property 'toBeArray' does not exist on type 'Matchers'.
app/services/tree.service.spec.ts(40,29): error TS2339: Property 'toBeNonEmptyArray' does not exist on type 'Matchers'.
```

So I don't know how to import this matcher inside the Spec file.

Any help is appreciate ;)

Thanks!

**[EDIT]** 
As I mentioned, I believe this is not an issue, because I finally solve this problem. I've missed some important thing to do, considering I'm using TypeScript:

`typings install dt~jasmine-expect --save-dev -DG`

With this, a `globalDevDependencies` is added in file `typings.json` and this library is available to use.

I think that the documentation is great and very useful, but maybe it could be improve with a section explain how to use with TypeScript.

Thanks a lot!

### PR DESCRIPTION
**Pull request by aaronbroad**
to resolve #59

### CODE REVIEW

**Comment by ikasparov** [comment]
👍  thanks man

**Comment by JamieMason** [comment]
Thanks a lot @aaronbroad, just an update as it's been a while. I started a branch locally to switch this project over to TypeScript and have been referencing this PR while doing it. 1. It means the generated declarations file should always be up to date and 2. personally, it's a good way for me to try out and learn TS.

I've not had time since then to work on any of my open source projects but this is high up the list when I do get time again. 

Thanks.

**Comment by JamieMason** [comment]
Hey,
I've pushed https://github.com/JamieMason/Jasmine-Matchers/tree/pull-request/62-typings with your changes and some of the newer matchers added on top. 

One thing I'm wondering is, should `jasmine-matchers.d.ts` reference jasmine's typings in some way? Like Definitely Typed does at [DefinitelyTyped/jasmine-expect/jasmine-expect.d.ts#L6](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jasmine-expect/jasmine-expect.d.ts#L6). Does TypeScript need to be told somehow that this library is extending jasmine and not creating something separate which uses the same namespaces?

**Comment by aaronbroad** [comment]
I don't think you need to reference jasmine's typings. If you want, we could include jasmine's types in the package.json file (I don't believe jasmine includes typing definitions in its npm package yet.) 
```
"devDependencies":
   ...
    "@types/jasmine": "2.4.1"
```

**Comment by luchsamapparat** [comment]
Hi,

Any plans to merge this?

**Comment by JoshuaKGoldberg** [comment]
@JamieMason but can you merge pull requests for TypeScript typings so we're unblocked?

**Comment by JamieMason** [comment]
sure, give me 10-15 mins

**Comment by JamieMason** [comment]
This has been merged as https://github.com/JamieMason/Jasmine-Matchers/commit/105bcc33a42a70d01bc50177e128358ac257e199. I've a better grasp of TypeScript now so will be able to maintain this from here.

Thanks a lot, and sorry for such a long wait.

**Pull request closed without merging**
