### PR TITLE
docs(readme): replace semicolons with colons

### PR DESCRIPTION
**Pull request by bennyn**

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks a lot for this @bennyn. I would want to change the commit message to `docs(readme): replace semicolons with colons` but I'm happy to do that myself when I come to merge this, no problem.

**Comment by bennyn** [comment]
Don't worry. I changed it. :) Happy to see, that you are using [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages).

**Comment by JamieMason** [comment]
Thanks! the [commit](https://github.com/JamieMason/Jasmine-Matchers/pull/88/commits/0c9f0dbf53fd099d6206ab9d58ad4920be7069ba) still seems to have the old message though, did you push?

**Comment by bennyn** [comment]
@JamieMason: I changed it in the title of the PR and now also in the original commit. :) Please verify.

**Comment by JamieMason** [comment]
Merged! 🎉  thanks a lot

**Pull request merged**
