### PR TITLE
WIP: Add toBeSet matcher

### PR DESCRIPTION
**Pull request by jrencz**
Refs #43

### CODE REVIEW

**Comment by jrencz** [comment]
@JamieMason maybe we should include [JasonBerry/babel-es6-polyfill](https://github.com/JasonBerry/babel-es6-polyfill) just for tests then?

**Comment by JamieMason** [comment]
I don't think we need as much as that, plus I think would also impose porting this project to Babel? 

This is a tricky one, but it _should_ just be a case of setting up the conditions needed for just this test within it's own `beforeEach`.

```
toBeSet
    beforeEach: mock global.Set
    when invoked
        when subject IS a Set
            should confirm
        when subject is NOT a Set
            should deny
```

In the case where `Set` is not supported (by "support" I include polyfills) then it should be expected that the user should get a `ReferenceError` in their suite for the given browser — as this will show them what would happen in their actual product and prompt them to polyfill for those browsers so that the functionality they were trying to use is available.

Does that sound right to you?

**Comment by JamieMason** [comment]
Something I've since done on other projects (and probably should have done on this one) is define a `globals.js` module which can be substituted for mocks during test.

This is one from another project (`module.exports = Object.create(window);` is not possible sadly, as even overwriting methods on the instance results in a noop).

```
'use strict';

module.exports = {
    clearInterval: window.clearInterval.bind(window),
    Date: window.Date,
    document: window.document,
    JSON: window.JSON,
    localStorage: window.localStorage,
    Promise: window.Promise,
    setInterval: window.setInterval.bind(window)
};
```

Anyway, for this project that would mean, among others;

```
'use strict';

module.exports = {
    Set: window.Set.bind(window)
};
```

Which could then be mocked in test.

**Comment by jrencz** [comment]
> I don't think we need as much as that, plus I think would also impose porting this project to Babel?

Babel itself is about syntax. `browser-polyfill.js` is about host objects and new methods.
We don't have to use Babel to use the polyfill. Polyfill used to be a part of Babel project once.

**Comment by JamieMason** [comment]
I see, ok thanks for explaining that.

**Comment by JamieMason** [comment]
Thanks again for raising this @jrencz but I've decided not to add matchers for `Set` etc. A new project such as jasmine-set-matchers could be useful to people though if you decide to take it on.

**Pull request closed without merging**
