### PR TITLE
Add expect(floatNumber).toBeNear(number, epsilon) #58

### PR DESCRIPTION
**Pull request by jacobwarduk**

### CODE REVIEW

**Comment by JamieMason** [comment]
Merged and [building on develop](https://travis-ci.org/JamieMason/Jasmine-Matchers/builds/192125442).

**Comment by jacobwarduk** [comment]
I've noticed there are conflicts. Would you like me to resolve them?

**Comment by JamieMason** [comment]
That's ok.

What this is saying is that, now your commits are in develop and have been modified, this PR now conflicts with _that_ new version of develop.

**Comment by JamieMason** [comment]
Released in 3.5.0 🎉

**Pull request closed without merging**
